/**
 * Tests for the reference implementation and the vector set.
 *
 * The vectors were generated by reference/jcs.mjs, so a suite that only checked
 * the reference against them would be circular and would pass even if the
 * reference were wrong. The assertions below are therefore hand-written from
 * RFC 8785 and SPEC §2.1, independently of what the reference produces.
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { canonicalize, canonicalizeLegacySortRebuild } from '../reference/jcs.mjs';
import { signingInputHex } from '../reference/signing-input.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const load = (set) => JSON.parse(readFileSync(join(HERE, '..', 'vectors', `${set}.json`), 'utf8'));

describe('RFC 8785 — hand-written assertions', () => {
  test('integer-like keys sort by code unit, not numerically', () => {
    // '1' (U+0031) precedes '2' (U+0032), so "10" precedes "2".
    assert.equal(canonicalize({ '2': 'two', '10': 'ten' }), '{"10":"ten","2":"two"}');
  });

  test('sort-then-rebuild disagrees, which is the whole problem', () => {
    const input = { '2': 'two', '10': 'ten' };
    assert.equal(canonicalizeLegacySortRebuild(input), '{"2":"two","10":"ten"}');
    assert.notEqual(canonicalizeLegacySortRebuild(input), canonicalize(input));
  });

  test('key order in the source object never affects output', () => {
    assert.equal(canonicalize({ b: 1, a: 2 }), canonicalize({ a: 2, b: 1 }));
    assert.equal(canonicalize({ b: 1, a: 2 }), '{"a":2,"b":1}');
  });

  test('uppercase sorts before underscore, which sorts before lowercase', () => {
    // U+0041 'A' < U+005F '_' < U+0061 'a'. A locale-aware sort gets this wrong.
    assert.equal(canonicalize({ a: 1, _: 2, A: 3 }), '{"A":3,"_":2,"a":1}');
  });

  test('array order is preserved', () => {
    assert.equal(canonicalize([3, 1, 2]), '[3,1,2]');
  });

  test('numbers use ECMAScript Number::toString', () => {
    assert.equal(canonicalize({ a: 1.0 }), '{"a":1}');
    assert.equal(canonicalize({ a: -0 }), '{"a":0}');
    assert.equal(canonicalize({ a: 1e21 }), '{"a":1e+21}');
  });

  test('non-finite numbers are rejected rather than coerced', () => {
    assert.throws(() => canonicalize({ a: NaN }), TypeError);
    assert.throws(() => canonicalize({ a: Infinity }), TypeError);
  });

  test('bigint is rejected rather than silently stringified', () => {
    assert.throws(() => canonicalize({ a: 1n }), TypeError);
  });

  test('undefined members are dropped from objects, null-filled in arrays', () => {
    assert.equal(canonicalize({ a: 1, b: undefined }), '{"a":1}');
    assert.equal(canonicalize([1, undefined, 2]), '[1,null,2]');
  });

  test('circular references throw instead of hanging', () => {
    const o = { a: 1 };
    o.self = o;
    assert.throws(() => canonicalize(o), /circular/);
  });

  test('astral characters and escapes survive intact', () => {
    assert.equal(canonicalize({ e: '\u{1F0CF}' }), '{"e":"🃏"}');
    assert.equal(canonicalize({ q: 'a"b' }), '{"q":"a\\"b"}');
  });
});

describe('SPEC §2.1 signing input — hand-written assertions', () => {
  const base = {
    v: 'vg-attest/2',
    type: 'Grade',
    payload: { b: 1, a: 2 },
    references: [{ type: 'Capture', hash: 'sha256:aa' }],
  };

  test('retrieval does not affect the digest', () => {
    // Where an envelope can be obtained may change over its life without altering
    // what was attested, so `retrieval` sits outside the signed bytes (SPEC §2.1).
    const withRetrieval = { ...base, retrieval: { profile: 'inscribed' } };
    assert.equal(signingInputHex(withRetrieval), signingInputHex(base));
  });

  test('signatures and anchor do not affect the digest', () => {
    const withExtras = {
      ...base,
      signatures: [{ role: 'kiosk', sig: 'zz' }],
      anchor: { certificate: { payloadHash: 'ff' } },
    };
    assert.equal(signingInputHex(withExtras), signingInputHex(base));
  });

  test('payload key order does not affect the digest', () => {
    assert.equal(signingInputHex({ ...base, payload: { a: 2, b: 1 } }), signingInputHex(base));
  });

  test('envelope type is domain-separated', () => {
    assert.notEqual(signingInputHex({ ...base, type: 'GradeOverride' }), signingInputHex(base));
  });

  test('envelope version is domain-separated', () => {
    assert.notEqual(signingInputHex({ ...base, v: 'vg-attest/3' }), signingInputHex(base));
  });

  test('reference order is part of the signed bytes', () => {
    const two = { ...base, references: [{ h: 'a' }, { h: 'b' }] };
    const flipped = { ...base, references: [{ h: 'b' }, { h: 'a' }] };
    assert.notEqual(signingInputHex(two), signingInputHex(flipped));
  });

  test('an unversioned envelope is refused, not silently signed', () => {
    const { v, ...noVersion } = base;
    assert.throws(() => signingInputHex(noVersion), /envelope\.v is required/);
  });

  test('a typeless envelope is refused', () => {
    const { type, ...noType } = base;
    assert.throws(() => signingInputHex(noType), /envelope\.type is required/);
  });

  test('digest is 32 bytes of lowercase hex', () => {
    assert.match(signingInputHex(base), /^[0-9a-f]{64}$/);
  });
});

describe('the reference reproduces every published vector', () => {
  for (const c of load('canonical').cases) {
    test(`canonical/${c.name}`, () => {
      assert.equal(canonicalize(c.input), c.expected);
    });
  }
  for (const c of load('signing-input').cases) {
    test(`signing-input/${c.name}`, () => {
      assert.equal(signingInputHex(c.envelope), c.expected);
    });
  }
});

describe('the vector set covers what it claims to', () => {
  test('at least one canonical case distinguishes JCS from sort-then-rebuild', () => {
    const differing = load('canonical').cases.filter((c) => c.legacyDiffers);
    assert.ok(differing.length >= 3, `expected >= 3 discriminating cases, got ${differing.length}`);
  });

  test('every legacyDiffers flag is accurate', () => {
    for (const c of load('canonical').cases) {
      const differs = canonicalizeLegacySortRebuild(c.input) !== canonicalize(c.input);
      assert.equal(differs, c.legacyDiffers, `${c.name}: legacyDiffers is stale`);
    }
  });
});
